name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --target=build
      - run: find ./dist/ -name package.json -execdir npm publish \;
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}